import Image from "next/image";
import AboutUs from "../components/AboutUs";

export const metadata = {
  title: "about-us",
  description: "Generated by create next app",
};

export default function Page() {
  return (
   <>
   <AboutUs/>
   </>

  );
}
